:PROPERTIES:
:ID:       480d0eef-cef1-4d85-b7a0-4727718b36f3
:END:
#+title: Google Cybersecurity Professional Certificate - Course 02 | Week 03
#+hugo_custom_front_matter: :summary Week Three of Google's Cybersecurity Certification, Play It Safe: Manage Security Risks
#+hugo_date: [2023-07-31 Mon]
#+hugo_auto_set_lastmod: Time-stamp: <2023-08-07 17:03:56 (adelgado)>
#+hugo_code_fence: nil
#+hugo_section: notes
#+hugo_draft: false
#+hugo_tags: cybersecurity certificates google
#+property: header-args :dir run :mkdirp yes :padline no :exports both :results code :eval no-export
#+export_file_name: google_cybersecurity_professional_certificate_course_02_week_03

* Play It Safe - Manage Security Risks: Week Three

Explore industry leading security information and event management (SIEM) tools used by security professionals to protect business operations.

 + Identify and define commonly used SIEM tools
 + Describe how SIEM tools are used to protect business operations

** Security Information and Event Management (SIEM) Dashboards

As a security analyst you will analyze log data to mitigate and manage threates, risks, and vulnerabilities; such as firewall, network, and server logs.

#+begin_quote
Log
A record of events that occur within an organization's systems and networks.
#+end_quote

A firewall log is a record of attempted or established connections for incoming traffic from the internet, as well as outbound requests to the internet from within the network.

A network log is a record of all computers and devices that enter and leave the network, as well as connections between devices and services on the network.

A server log is a record of events related to services such as websites, emails, or file shares, including login, password, and username requests.

A SIEM tool is an application that collects and analyzes log data to monitor critical activities in an organization. Provides real-time visibility, event monitoring and analysis, and automated alerts while storing log data in a centralized location.

SIEM tools isn't an out of the box solution, it must be configured and customized to meet an organization's unique security needs.

With SIEM tools, dashboards can be created to better visualize the data. Providing metrics for stakeholders such as response time, availability, and failure rate to help assess the performance of a software application.

Currently SIEM tools required human interaction, but with the changing nature of technology, SIEM capabilities will grow with advancements in artifical intelligence (AI) and machine learning (ML). With automation implementation, it will help in faster response times without human response.

Security orchestration, automation, and response (SOAR) is a collection of applications, tools, and workflows that uses automation to respond to security events.

** Explore SIEM Tools

Self-hosted SIEM tools require organizations to install, operate, and maintain the tool using their own physical infrastructure, such as server capacity. Ideal when requiring to maintain physical control over confidential data.

Clouse-hosted SIEM tools are maintained and managed by the SIEM providers, making them accessible through the internet. Ideal when no wanting to invest in creating and maintaining their own infrastructure.

Doesn't mean you must go all-in on one solution, you can have a mixed of both, hybrid solution, depending on the needs that need to be met for the organization.

*** Splunk

Splunk is a data analysis platform that provides a self-hosted and cloud-hosted solution. Splunk Enterprise is a self-hosted tool used to retain, analyze, and search log data and provide real time alerts. Splunk Cloud is a cloud-hosted tool that collects, searches, and monitors log data.

Different types of Splunk dashboards:

*Security Posture Dashboard*

The security posture dashboard is designed for security operations centers (SOCs). It displays the last 24 hours of an organization’s notable security-related events and trends and allows security professionals to determine if security infrastructure and policies are performing as designed. Security analysts can use this dashboard to monitor and investigate potential threats in real time, such as suspicious network activity originating from a specific IP address.

*Executive Summary Dashboard*

The executive summary dashboard analyzes and monitors the overall health of the organization over time. This helps security teams improve security measures that reduce risk. Security analysts might use this dashboard to provide high-level insights to stakeholders, such as generating a summary of security incidents and trends over a specific period of time.

*Incident Review Dashboard*

The incident review dashboard allows analysts to identify suspicious patterns that can occur in the event of an incident. It assists by highlighting higher risk items that need immediate review by an analyst. This dashboard can be very helpful because it provides a visual timeline of the events leading up to an incident.

*Risk analysis dashboard*

The risk analysis dashboard helps analysts identify risk for each risk object (e.g., a specific user, a computer, or an IP address). It shows changes in risk-related activity or behavior, such as a user logging in outside of normal working hours or unusually high network traffic from a specific computer. A security analyst might use this dashboard to analyze the potential impact of vulnerabilities in critical assets, which helps analysts prioritize their risk mitigation efforts.

*** Google Chronicle

Google Chronicle is a cloud-native tool that retains, analyzes, and searches data. Providing log monitoring, data analysis, and data collection.

*Enterprise insights dashboard*

The enterprise insights dashboard highlights recent alerts. It identifies suspicious domain names in logs, known as indicators of compromise (IOCs). Each result is labeled with a confidence score to indicate the likelihood of a threat. It also provides a severity level that indicates the significance of each threat to the organization. A security analyst might use this dashboard to monitor login or data access attempts related to a critical asset—like an application or system—from unusual locations or devices.

*Data ingestion and health dashboard*

The data ingestion and health dashboard shows the number of event logs, log sources, and success rates of data being processed into Chronicle. A security analyst might use this dashboard to ensure that log sources are correctly configured and that logs are received without error. This helps ensure that log related issues are addressed so that the security team has access to the log data they need.

*IOC matches dashboard*

The IOC matches dashboard indicates the top threats, risks, and vulnerabilities to the organization. Security professionals use this dashboard to observe domain names, IP addresses, and device IOCs over time in order to identify trends. This information is then used to direct the security team’s focus to the highest priority threats. For example, security analysts can use this dashboard to search for additional activity associated with an alert, such as a suspicious user login from an unusual geographic location.

*Main dashboard*

The main dashboard displays a high-level summary of information related to the organization’s data ingestion, alerting, and event activity over time. Security professionals can use this dashboard to access a timeline of security events—such as a spike in failed login attempts— to identify threat trends across log sources, devices, IP addresses, and physical locations.

*Rule detections dashboard*

The rule detections dashboard provides statistics related to incidents with the highest occurrences, severities, and detections over time. Security analysts can use this dashboard to access a list of all the alerts triggered by a specific detection rule, such as a rule designed to alert whenever a user opens a known malicious attachment from an email. Analysts then use those statistics to help manage recurring incidents and establish mitigation tactics to reduce an organization's level of risk.

*User sign in overview dashboard*

The user sign in overview dashboard provides information about user access behavior across the organization. Security analysts can use this dashboard to access a list of all user sign-in events to identify unusual user activity, such as a user signing in from multiple locations at the same time. This information is then used to help mitigate threats, risks, and vulnerabilities to user accounts and the organization’s applications.

*** Open-source & Proprietary

Open-source tools are often free to use and can be user friendly, with the objective that it is tools built collaboratively by the public which can make the software more secure.

Proprietary tools are developed and owned by a person or company and typically a fee must be paid for usage and training. Owners of the tools are the only ones who can access / modify the source code, which means one must wait for updates to be made to the tool and at times be charged a fee for said updates.

Don't let the misconception that open-source tools are less effective than proprietary ones, do your research and due dilligence!

Linux is an open-source operating system that is widely used.

Suricata is an open-source network analysis and threat detection software, which inspects network traffic to identify suspicious behavior and generate network data logs across users, cmputers or IP addresses. Developed by the Open Information Security Foundation (OISF), which is dedicated in maintaining open-source use of the Suricata project to ensure it's free and publicly available.
