#+title: Google Cybersecurity Professional Certificate - Course 01 | Week 02
#+hugo_custom_front_matter: :summary Week Two of Google's Cybersecurity Certification, Foundations of Cybersecurity
#+hugo_code_fence: nil
#+hugo_section: notes
#+hugo_draft: false
#+hugo_tags: cybersecurity certificates google
#+property: header-args :dir run :mkdirp yes :padline no :exports both :results code :eval no-export
#+export_file_name: google-cybersec-cert-crse-01-wk-02

* Foundations of Cybersecurity: Week Two

Covering Topics
 + Viruses
 + Malware
 + Social Engineering
 + Digital Age
 + Security Domains

** History of Cybersecurity

#+begin_quote
Computer Virus
Malicious code written to interfere with computer operations and cause damage to data and software
#+end_quote

A worm is a type of computer virus that spreads and duplicates on its own without human involvement.

In 1986, the Alvi brothers created the Brain virus, with the intention to track illegal copies of medical software and prevent pirated licenses. It would infect the hosts computer when a pirate copy of the software was used but unexpectedly would infect any other disk inserted into the system afterwards. This would make the virus spread to a new computer whenever someone used one of the infected disks which went undetected and spread globally within a few months severely slowing down productivty and impacting business operations.

In 1988, the Morris worm came to be which was developed by Robert Morris as a program to assess the size of the internet. The program crawled the web and installed itself onto computers to get a count of computers that were coneccted to the internet, but, it failed to keep track of already compromised computers and kept re-installing itself until the computers ran out of memory and crashed. The worm affected 10% of the internet at the time, around 6000 computers. After the Morris worm, Computer Emergency Response Teams (CERTs) were established to respond to computer security incidents.

Now in the digital age and with the expansion of high-speed internet and computers connected to the internet, malware can now be spread through the internet with no need of physical disks to spread viruses.

In 2000, Onel De Guzman created the LoveLetter malware to steal internet login credentials. It spread rapidly and took advantage of people not developing suspicion for unsolicited emails. A user would receive an email with the subject "I Love You" and contain and attachment "Love Letter For You" which when opened, would scan a user's address book and sending itself to each email address within while at the same time installing a program to collect user information and passwords.

#+begin_quote
Malware
Software designed to harm devices or networks
#+end_quote

 + *Viruses*: Malicious code written to interfere with computer operations and cause damage to data, software, and hardware. A virus attaches itself to programs or documents, on a computer. It then spreads and infects one or more computers in a network.
 + *Worms*: Malware that can duplicate and spread itself across systems on its own.
 + *Ransomware*: A malicious attack where threat actors encrypt an organization's data and demand payment to restore access.
 + *Spyware*: Malware that’s used to gather and sell information without consent. Spyware can be used to access devices. This allows threat actors to collect personal data, such as private emails, texts, voice and image recordings, and locations.

#+begin_quote
Social Engineering
A manipulation technique that exploits human error to gain private information, access, or valuables
#+end_quote

 + *Social media phishing*: A threat actor collects detailed information about their target from social media sites. Then, they initiate an attack.
 + *Watering hole attack*: A threat actor attacks a website frequently visited by a specific group of users.
 + *USB baiting*: A threat actor strategically leaves a malware USB stick for an employee to find and install, to unknowingly infect a network.
 + *Physical social engineering*: A threat actor impersonates an employee, customer, or vendor to obtain unauthorized access to a physical location.

#+begin_quote
Phishing
The use of digital communications to trick people into revealing sensitive data or deploying malicious software
#+end_quote

 + *Business Email Compromise (BEC)*: A threat actor sends an email message that seems to be from a known source to make a seemingly legitimate request for information, in order to obtain a financial advantage.
 + *Spear phishing*: A malicious email attack that targets a specific user or group of users. The email seems to originate from a trusted source.
 + *Whaling*: A form of spear phishing. Threat actors target company executives to gain access to sensitive data.
 + *Vishing*: The exploitation of electronic voice communication to obtain sensitive information or to impersonate a known source.
 + *Smishing*: The use of text messages to trick users, in order to obtain sensitive information or to impersonate a known source.

Social engineering attacks increases with every new social media application that allows public access to people's data. It can be convenient to share locations and photos it comes with a risk.

 + *Authority*: Threat actors impersonate individuals with power. This is because people, in general, have been conditioned to respect and follow authority figures.
 + *Intimidation*: Threat actors use bullying tactics. This includes persuading and intimidating victims into doing what they’re told.
 + *Consensus/Social proof*: Because people sometimes do things that they believe many others are doing, threat actors use others’ trust to pretend they are legitimate. For example, a threat actor might try to gain access to private data by telling an employee that other people at the company have given them access to that data in the past.
 + *Scarcity*: A tactic used to imply that goods or services are in limited supply.
 + *Familiarity*: Threat actors establish a fake emotional connection with users that can be exploited.
 + *Trust*: Threat actors establish an emotional relationship with users that can be exploited over time. They use this relationship to develop trust and gain personal information.
 + *Urgency*: A threat actor persuades others to respond quickly and without questioning.

** Certified Information Systems Security Professional (CISSP) Security Domains

As of 2022, CISSP has defined eight domains to organize the work of security professionals and it is important to understand that the domains are related and gaps in one domain can result in negative consequences to an entire organization.

**** Security and Risk Management

This domain defines security goals and objectives, risk mitigation, compliance, business continuity, and the law. As an example, security analysts may need to update company policies related to private health information if a change is made to the Health Insurance Portability and Accountability Act (HIPAA).

**** Asset Security

This domain secures digital and physical assets and is also related to the storage, maintenance, retention, and destruction of data. Security analysts may be tasked with making sure that old equipment is properly disposed of and destroyed, including any type of confidential information.

**** Security Architecture and Engineering

This domain focuses on optimizing data security by ensuring effective tools, systems, and processes are in place. Configuring a firewall may be a task as a security analyst to help prevent attacks that could affect productivity.

**** Communication and Network Security

This domain focuses on managing and securing physical networks and wireless communications. You may be asked, as a security analyst, to analyze user behavior within your organization, discovering that users are connecting to unsecured WiFi hotspots. Leaving an organization and employees vulnerable to attacks and as such ensure that communications are secure by creating a network policy to prevent and mitigate exposure.

**** Identity and Access Management

This domain focuses on keeping data secure by ensuring users follow established policies to control and manage physical assets, like office spaces, and logical assets, such as networks and applications. A task as a security analyst may be to setup emplyees' keycard access to buildings.

**** Security Assesment and Testing

This domain focuses on conducting security control testing, collecting and analyzing data, and conducting security audits to monitor for risks, threats, and vulnerabilities. As a security analyst you may conduct regulat audits of user permissions, to make sure that users have the correct level of access, like accessing payroll information which is limited to certain employees and may regularly audit permissions so unauthorized users can't view employee salaries.

**** Security Operations

This domain focuses on conducting investigations and implementing preventative measures. Say you receive an alert that an unknown device has connected to your internal network and would quickly follow the organization's policies and procedures to stop the potential threat.

**** Software Development Security

This domain focuses on using secure coding practices to create secure applications and services. You may work with software development teams to ensure security practices are incorporated into the software development life-cycle, like advising on proper password policies or ensure user data is properly secured and managed.

*** Types of Attacks

Password attack, an attempt to access password-secured devices, systems, networks, or data; Brute Force and Rainbow Table being forms of password attacks. This type of attack would fall under the domain *communication and network security*.

Social engineering attack, a manipulation techqnique that explots human error to gain private information, access, or valuables. This type of attack would fall under the domain *security and risk management*.

Physical attack, security incident that affects both digital and physical environments. This type of attack would fall under the domain *asset security*.

Adversarial artificial intelligence, a technique that manipulates AI and ML technology to conduct attacks more efficiently. This type of attack would fall under the domains *communication and network security* and *identity and access management*.

Supply-chain attack targets systems, applications, hardware, and/or software to locate a vulnerability for malware deployment. Since goods sold involve third parties, a security breach can happen at any point in the supply chain and can affect multiple organizations and individuals who work for them. This type of attack falls under several domains which includes but is not limited to *security and risk management*, *security architecture and engineering*, *security operations*.

Cryptographic attack affects secure forms of communication between a sender and intended recipient and fall under the domain *communication and network security*.

*** Understand Attackers

**** Threat Actor Types

*Advanced persistent threats* (APTs) have significant expertise accessing an organization's network without authorization. APTs tend to research their targets (e.g., large corporations or government entities)  in advance and can remain undetected for an extended period of time. Their intentions and motivations can include:

 + Damaging critical infrastructure, such as the power grid and natural resources
 + Gaining access to intellectual property, such as trade secrets or patents

*Insider threats* abuse their authorized access to obtain data that may harm an organization. Their intentions and motivations can include:

 + Sabotage
 + Corruption
 + Espionage
 + Unauthorized data access or leaks

*Hacktivists* are threat actors that are driven by a political agenda. They abuse digital technology to accomplish their goals, which may include:

 + Demonstrations
 + Propaganda
 + Social change campaigns
 + Fame

**** Hacker Types

A *hacker* is any person who uses computers to gain access to computer systems, networks, or data. They can be beginner or advanced technology professionals who use their skills for a variety of reasons. There are three main categories of hackers:

 + Authorized hackers are also called ethical hackers. They follow a code of ethics and adhere to the law to conduct organizational risk evaluations. They are motivated to safeguard people and organizations from malicious threat actors.
 + Semi-authorized hackers are considered researchers. They search for vulnerabilities but don’t take advantage of the vulnerabilities they find.
 + Unauthorized hackers are also called unethical hackers. They are malicious threat actors who do not follow or respect the law. Their goal is to collect and sell confidential data for financial gain.

There are multiple hacker types that fall into one or more of these three categories.

New and unskilled threat actors have various goals, including:

 + To learn and enhance their hacking skills
 + To seek revenge
 + To exploit security weaknesses by using existing malware, programming scripts, and other tactics

Other types of hackers are not motivated by any particular agenda other than completing the job they were contracted to do. These types of hackers can be considered unethical or ethical hackers. They have been known to work on both illegal and legal tasks for pay.

There are also hackers who consider themselves vigilantes. Their main goal is to protect the world from unethical hackers.
