#+title: Google Cybersecurity Professional Certificate - Week Two
#+hugo_custom_front_matter: :summary Week Two of Google's Cybersecurity Certification
#+hugo_auto_set_lastmod: t
#+hugo_code_fence: nil
#+hugo_section: synapse
#+hugo_draft: false
#+hugo_tags: cybersecurity certificates google
#+property: header-args :dir run :mkdirp yes :padline no :exports both :results code :eval no-export
#+export_file_name: google-cybersec-cert-week-two

* Foundations of Cybersecurity: Week 2

Covering Topics
 + Viruses
 + Malware
 + Social Engineering
 + Digital Age
 + Security Domains

** History of Cybersecurity

#+begin_quote
Computer Virus
Malicious code written to interfere with computer operations and cause damage to data and software
#+end_quote

A worm is a type of computer virus that spreads and duplicates on its own without human involvement.

In 1986, the Alvi brothers created the Brain virus, with the intention to track illegal copies of medical software and prevent pirated licenses. It would infect the hosts computer when a pirate copy of the software was used but unexpectedly would infect any other disk inserted into the system afterwards. This would make the virus spread to a new computer whenever someone used one of the infected disks which went undetected and spread globally within a few months severely slowing down productivty and impacting business operations.

In 1988, the Morris worm came to be which was developed by Robert Morris as a program to assess the size of the internet. The program crawled the web and installed itself onto computers to get a count of computers that were coneccted to the internet, but, it failed to keep track of already compromised computers and kept re-installing itself until the computers ran out of memory and crashed. The worm affected 10% of the internet at the time, around 6000 computers. After the Morris worm, Computer Emergency Response Teams (CERTs) were established to respond to computer security incidents.

Now in the digital age and with the expansion of high-speed internet and computers connected to the internet, malware can now be spread through the internet with no need of physical disks to spread viruses.

In 2000, Onel De Guzman created the LoveLetter malware to steal internet login credentials. It spread rapidly and took advantage of people not developing suspicion for unsolicited emails. A user would receive an email with the subject "I Love You" and contain and attachment "Love Letter For You" which when opened, would scan a user's address book and sending itself to each email address within while at the same time installing a program to collect user information and passwords.

#+begin_quote
Malware
Software designed to harm devices or networks
#+end_quote

 + *Viruses*: Malicious code written to interfere with computer operations and cause damage to data, software, and hardware. A virus attaches itself to programs or documents, on a computer. It then spreads and infects one or more computers in a network.
 + *Worms*: Malware that can duplicate and spread itself across systems on its own.
 + *Ransomware*: A malicious attack where threat actors encrypt an organization's data and demand payment to restore access.
 + *Spyware*: Malware that’s used to gather and sell information without consent. Spyware can be used to access devices. This allows threat actors to collect personal data, such as private emails, texts, voice and image recordings, and locations.

#+begin_quote
Social Engineering
A manipulation technique that exploits human error to gain private information, access, or valuables
#+end_quote

 + *Social media phishing*: A threat actor collects detailed information about their target from social media sites. Then, they initiate an attack.
 + *Watering hole attack*: A threat actor attacks a website frequently visited by a specific group of users.
 + *USB baiting*: A threat actor strategically leaves a malware USB stick for an employee to find and install, to unknowingly infect a network.
 + *Physical social engineering*: A threat actor impersonates an employee, customer, or vendor to obtain unauthorized access to a physical location.

#+begin_quote
Phishing
The use of digital communications to trick people into revealing sensitive data or deploying malicious software
#+end_quote

 + *Business Email Compromise (BEC)*: A threat actor sends an email message that seems to be from a known source to make a seemingly legitimate request for information, in order to obtain a financial advantage.
 + *Spear phishing*: A malicious email attack that targets a specific user or group of users. The email seems to originate from a trusted source.
 + *Whaling*: A form of spear phishing. Threat actors target company executives to gain access to sensitive data.
 + *Vishing*: The exploitation of electronic voice communication to obtain sensitive information or to impersonate a known source.
 + *Smishing*: The use of text messages to trick users, in order to obtain sensitive information or to impersonate a known source.

Social engineering attacks increases with every new social media application that allows public access to people's data. It can be convenient to share locations and photos it comes with a risk.

 + *Authority*: Threat actors impersonate individuals with power. This is because people, in general, have been conditioned to respect and follow authority figures.
 + *Intimidation*: Threat actors use bullying tactics. This includes persuading and intimidating victims into doing what they’re told.
 + *Consensus/Social proof*: Because people sometimes do things that they believe many others are doing, threat actors use others’ trust to pretend they are legitimate. For example, a threat actor might try to gain access to private data by telling an employee that other people at the company have given them access to that data in the past.
 + *Scarcity*: A tactic used to imply that goods or services are in limited supply.
 + *Familiarity*: Threat actors establish a fake emotional connection with users that can be exploited.
 + *Trust*: Threat actors establish an emotional relationship with users that can be exploited over time. They use this relationship to develop trust and gain personal information.
 + *Urgency*: A threat actor persuades others to respond quickly and without questioning.

** Certified Information Systems Security Professional (CISSP) Security Domains
