:PROPERTIES:
:ID:       acbcd7fd-a200-4da9-911a-abadca83f1ca
:END:
#+TITLE: Kubernetes Absolute Beginner
#+DESCRIPTION: Notes pertaining to the KodeKloud Kubernetes Absolute Beginner course
#+hugo_lastmod: Time-stamp: <2022-03-20 22:29:48 (arterro)>

* Kubernetes Overview

-----

Kubernetes (K8s) was initially built by Google but is now an open-source project (CNCF).

** Containers Overview

Containers are not a new concept and they've been around for 10+ years. They exist in other forms like LXC (hard, low-level) but Docker has become the defacto standard due to the ease it brings at a higher level to create containers.

Containers are completely isolated environments that can contain their own processes / network interfaces / mounts but share the same OS kernel.

Sharing the same OS kernel means that Docker can run any OS as long as it shares the kernel of the host operating system. An example woul be Ubuntu, a linux kernel, allows us to run any type of Linux OS in a container like Gentoo, Debian, Arch and so forth. Alternatively, we would not be able to run a Windows container on a linux based host as the kernerls differ and said container would need to be ran on a Windows host.

** Container Orchestration

Container Orchestration is the process of automatically deploying and managing containers, as such, Kubernetes is an orchestration technology.

*Advantages*
+ Application is highly available, hardware failures don't bring application down
+ Multiple instances of the application across different nodes
+ User traffic is load balanced across containers
+ Low hardware resources; easily scale up/down

** Kubernetes Architecture

  : Nodes
  : A physical / virtual worker machine where K8s is installed and containers are launched

If the node fails, what happens? Application goes down! (╥﹏╥)
Don't fear cause we have clusters!

  : Cluster
  : Set of nodes grouped together

If one node fails the application keeps chugging about as it can be accessed from the other nodes. Having multiple nodes also helps in sharing load.

Cool, who's gonna manage all of this (the cluster)?

  : Master
  : A node with k8s installed on it, configured as a master that watches over the nodes in the cluster.

Watches over the nodes in the cluster and is responsible for the orchestration of containrs on the worker nodes.

*** Components

When installing Kubernetes the following components are installed:

+ *API Server*
  - acts as the front-end for Kubernetes which users, management devices and CLI's communicate with to interact with clusters.
+ *etcd*
  - is a distributed reliable key-value store where Kubernetes stores all data used to manage the cluster. Responsible for implementing locks within the cluster to ensure there is no conflict between the masters.
+ *kubelet*
  - is the agent that runs on each node in the cluster making sure that the containers are running on the ndoes
+ *Container Runtime*
  - is the underlying software used to run contaiuners.
+ *Controller*
  - are the brains for orchestration, which are responsible for noticing and responding when nodes / containers / endpoints go down.
+ *Scheduler*
  - is responsible for distributing work / containers across multiple nodes by looking for newly created containers.

*** Master vs Worker Nodes

Worker nodes (minions) is where the containers are hosted.

Master nodes have the *kubelet* agent responsible for interacting with a master to provide health information on the worker nodes and carry out actions on them as well.

All information gathered on the master node is stored in a key-value store using *etcd*.

Also containers a *controller* and a *scheduler*.

* Setup Kubernetes

Can be setup locally directly on your host machine or a VM using solutions like *minikube* (dev friendly), *MicroK8s*, *Kubeadm* (production).

Can also be setup on the cloud using *Google Cloud Platform*, *Amazon Web Services*, *Azure*.

minikube is developer friendly and good for testing purposes, as it bundles all the different components into a single image, providing a pre-configured single node Kubernetes cluster provided as an ISO image.

* Kubernetes Concepts

Kubernetes does not deploy containers directly on the worker nodes; instead are encapsulated into a Kubernetes object known as a *Pod*.

  : Pod
  : Single instance of an application, the smallest object that can be created in Kubernetes.

Pods share a 1:1 relation with container images running the application. If you need to scale up, you add more pods and remove pods to scale down.

Pods can contain multiple images, doesn't have to be just one. For example, in the case of needing a helper container to go along with the application container.

#+begin_src shell
    # Creating a Pod with image pulled from Dockerhub
    kubectl run nginx --image nginx

    # View Pods
    kubectl get pods
#+end_src

* Kubernetes Concepts - PODs, ReplicaSets, Deployments

** Pods with YAML

Kubernetes uses YAML files as inputs for the creation of objects and follows the following structure for the four top level fields:

#+begin_src yaml
  # pod-definition.yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: myapp-pod
    labels:
      app: myapp
      type: front-end
  spec:
    containers:
      - name: nginx-container
        image: nginx
#+end_src
